"""create seasons table

Revision ID: 820b994ffa7c
Revises: d91d9200b65c
Create Date: 2024-12-10 14:50:44.633728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '820b994ffa7c'
down_revision: Union[str, None] = 'd91d9200b65c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seasons',
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Unicode(), nullable=True),
    sa.Column('first_aired', sa.Integer(), nullable=True),
    sa.Column('last_aired', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('series_id', 'season_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seasons')
    # ### end Alembic commands ###
