"""create series table

Revision ID: d91d9200b65c
Revises: 
Create Date: 2024-12-10 14:50:07.017763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd91d9200b65c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('series',
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Unicode(), nullable=True),
    sa.Column('series_info', sa.Unicode(), nullable=True),
    sa.Column('release_date', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('series_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('series')
    # ### end Alembic commands ###
